### PR TITLE
Markdown editor

### PR DESCRIPTION
**Pull request by Foine**
Provide a new renderer to have a markdown wysiwyg editor.

### CODE REVIEW

**Comment by felixgilles** [comment]
Top ! We have an issue on Novius OS and this renderer can be help to solve it : https://github.com/novius-os/novius-os/issues/38

**Comment by vrcAlbert** [comment]
Great renderer! I was not aware of the FuelPHP class Markdown, it's great to discover it.
As far as I'm concerned, I don't see any problems with the renderer (expect for coding style issue, see https://scrutinizer-ci.com/g/novius/novius_renderers/inspections/db7efdf9-ffd5-462b-ba84-28fb18dfb6d9/issues/files/classes/renderer/markdown/wysiwyg.php?status=new&orderField=path&order=asc).

I guess JS is okay too. (btw, I'm not sure if the credit is still OK for showdown.js, take a look at http://www.attacklab.net/ :P)

**Comment by vrcAlbert** [comment]
I made a PR on your repo to add french language. It seemed to be the last missing part to merge your PR :)

**Comment by Foine** [comment]
Perfect ! Thank you ! :D

**Pull request merged**
